### ISSUE TITLE
coroutines will block the execution of onGUI function

### ISSUE THREAD

**Issue by xiaoxiaowesley** [marijnz/unity-editor-coroutines#12]
I want to update a int number in Example function and display it in onGUI function. Then I found the onGUI function will be blocked .

See the log , the count number has updated to 2600 but the only display 2469.
It seem that the execution has block onGUI function.

![企业微信截图_a29838f7-6a6d-4678-b30d-2fec07130c05](https://user-images.githubusercontent.com/44207000/77029601-1a660480-69d7-11ea-950c-176e4156f98f.png)

**Comment by marijnz** [comment]
Heya, only seeing this now. I'd expect this behaviour because there's nothing refreshing the UI. You could manually call `Repaint` for it to update.
