### ISSUE TITLE
Namespace prevents using statements

### ISSUE THREAD

**Issue by mvi** [marijnz/unity-editor-coroutines#5]
Using statements can't be used because EditorCoroutines is both the namespace and class name. This requires fully qualifying every use of the class, which results in code bloat. Sharing the namespace and class name is ambiguous to the compiler, to resolve this the namespace could be changed to something like marijnz.EditorCoroutines

For example

```
using EditorCoroutines;

...

EditorCoroutines.StartCoroutine(foo, bar); // Won't compile due to ambiguous resolution
```

**Comment by SugoiDev** [comment]
Yeah, that's pretty important.

For travelers from the future, the [Framework design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces) has lots of useful info that can help with naming decisions.

**Comment by marijnz** [comment]
Hey, changed it. https://github.com/marijnz/unity-editor-coroutines/commit/6f418df16de82573d63b04473f0758a5d9769376. Thanks for the suggestion.
