### ISSUE TITLE
Editor folder instead of Scripts

### ISSUE THREAD

**Issue by excalith** [marijnz/unity-editor-coroutines#9]
Hello,

Thanks to editor coroutines, I have created huge editor tasks running smoothly for validating our levels working in cooperation with unit testing!

I just have a suggestion, renaming the `Scripts` folder into `Editor` can fix building issues (depending on how you used editor coroutines in your code) since they use UnityEditor namespace. It is no big deal actually, but might help someone dodge a few bullets later on while building - just to be safe. I can't see any downside of using `Editor` folder since it will be always an editor script anyways.

If you think it is okay to do so, I can send you PR with this tiny little change.

Cheers!

**Comment by marijnz** [comment]
Hi. Sounds good! If you make a PR, I will accept.
